server:
  port: 8080
#  context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true